_type: export
__export_format: 4
__export_date: 2024-06-17T03:56:57.214Z
__export_source: insomnia.desktop.app:v9.2.0
resources:
  - _id: req_114f3dd8a6ea45999a0f3ddb1dc30dd4
    parentId: fld_db37d18e49064fe1a253caf9e0f00440
    modified: 1718505155313
    created: 1718500974649
    url: "{{ _.url }}/security/signup"
    name: Sign Up
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"username": "estbm16",
        	"password": "usuario12345.",
        	"email": "stebanviz@gmail.com"
        }
    preRequestScript: ""
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication: {}
    metaSortKey: -1718500974649
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: fld_db37d18e49064fe1a253caf9e0f00440
    parentId: wrk_a36edb13ade64d769b9b18508a853132
    modified: 1718500812186
    created: 1718500812186
    name: Security
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1718500812186
    _type: request_group
  - _id: wrk_a36edb13ade64d769b9b18508a853132
    parentId: null
    modified: 1718500777861
    created: 1718500777861
    name: Importadora
    description: ""
    scope: collection
    _type: workspace
  - _id: req_8ae7748d2c4d43d08067a5dc9ae238b4
    parentId: fld_db37d18e49064fe1a253caf9e0f00440
    modified: 1718593243393
    created: 1718501004436
    url: "{{ _.url }}/security/api/token/"
    name: Login
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"username": "pperez",
        	"password": "empleado94"
        }
    preRequestScript: ""
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication: {}
    metaSortKey: -1718500894709
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_cbd86d96eeb44082ae224642de0c6519
    parentId: fld_db37d18e49064fe1a253caf9e0f00440
    modified: 1718500845803
    created: 1718500814769
    url: "{{ _.url }}/security/test"
    name: Test Security
    description: ""
    method: GET
    body: {}
    preRequestScript: ""
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/8.6.1
    authentication: {}
    metaSortKey: -1718500814769
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_e52d6389f30c4179b8404f4cd41af5ff
    parentId: fld_db37d18e49064fe1a253caf9e0f00440
    modified: 1718593782246
    created: 1718503799017
    url: "{{ _.url }}/security/test_token"
    name: Test token
    description: ""
    method: GET
    body: {}
    preRequestScript: ""
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/8.6.1
      - id: pair_d472faf13e5a422abb50caaf1da6093d
        name: ""
        value: ""
        description: ""
    authentication:
      type: bearer
      token: "{{ _.token }}"
      disabled: false
    metaSortKey: -1718500728295.5
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_89152168e82b4501b55d06bcfa657b7f
    parentId: fld_f24e44f2cca2456e9915f791e6d71a60
    modified: 1718595258513
    created: 1718511962297
    url: "{{ _.url }}/manager/employees"
    name: Get Employees
    description: ""
    method: GET
    body: {}
    preRequestScript: ""
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.token_empleado }}"
      disabled: false
    metaSortKey: -1718500771532.25
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: fld_f24e44f2cca2456e9915f791e6d71a60
    parentId: wrk_a36edb13ade64d769b9b18508a853132
    modified: 1718510903958
    created: 1718510903958
    name: Manager
    description: ""
    environment: {}
    environmentPropertyOrder: null
    metaSortKey: -1718500712584
    _type: request_group
  - _id: req_289a01ce21844f86a298043ccf60634f
    parentId: fld_f24e44f2cca2456e9915f791e6d71a60
    modified: 1718595424001
    created: 1718517153052
    url: "{{ _.url }}/manager/employee/3"
    name: Get Employee
    description: ""
    method: GET
    body: {}
    preRequestScript: ""
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.token_empleado }}"
      disabled: false
    metaSortKey: -1718500768829.9531
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_55c16eff29ae4d828847fdae07fd3d52
    parentId: fld_f24e44f2cca2456e9915f791e6d71a60
    modified: 1718595400964
    created: 1718513208115
    url: "{{ _.url }}/manager/employees"
    name: Create Employee
    description: ""
    method: POST
    body:
      mimeType: application/json
      text: |-
        {
        	"dni": "0104781422",
        	"first_name": "mariana",
        	"last_name": "enderica",
        	"email": "marianderica@gmail.com",
        	"position": "dev"
        }
    preRequestScript: ""
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.token }}"
      disabled: false
    metaSortKey: -1718500766127.6562
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_1c96e45589314e12aad790bcbc499362
    parentId: fld_f24e44f2cca2456e9915f791e6d71a60
    modified: 1718596523539
    created: 1718548050938
    url: "{{ _.url }}/manager/employee/3"
    name: Update Employee
    description: ""
    method: PUT
    body:
      mimeType: application/json
      text: |-
        {
        	"dni": "0104781422",
        	"first_name": "mariana de jesus",
        	"last_name": "enderica",
        	"email": "marianderica@gmail.com",
        	"position": "dev",
        	"phone": "0959697624",
        	"address": "San vicente de paccha"
        }
    preRequestScript: ""
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.token }}"
    metaSortKey: -1718500739104.6875
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_5b6d91b785e645e3945242769d974a4c
    parentId: fld_f24e44f2cca2456e9915f791e6d71a60
    modified: 1718596557369
    created: 1718596424720
    url: "{{ _.url }}/manager/employee/3"
    name: Update Employee Partial
    description: ""
    method: PATCH
    body:
      mimeType: application/json
      text: |-
        {
        	"phone": null,
        	"address": "Totoracocha"
        }
    preRequestScript: ""
    parameters: []
    headers:
      - name: Content-Type
        value: application/json
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.token }}"
    metaSortKey: -1718500736402.3906
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: req_62072c2349124d2e868463e29aa64548
    parentId: fld_f24e44f2cca2456e9915f791e6d71a60
    modified: 1718595396379
    created: 1718555619606
    url: "{{ _.url }}/manager/employee/2"
    name: Delete Employee
    description: ""
    method: DELETE
    body: {}
    preRequestScript: ""
    parameters: []
    headers:
      - name: User-Agent
        value: insomnia/8.6.1
    authentication:
      type: bearer
      token: "{{ _.token }}"
    metaSortKey: -1718500733700.0938
    isPrivate: false
    pathParameters: []
    settingStoreCookies: true
    settingSendCookies: true
    settingDisableRenderRequestBody: false
    settingEncodeUrl: true
    settingRebuildPath: true
    settingFollowRedirects: global
    _type: request
  - _id: env_1415ce00bca21418c66ca3faba539dc90feb06d9
    parentId: wrk_a36edb13ade64d769b9b18508a853132
    modified: 1718593254758
    created: 1718500777864
    name: Base Environment
    data:
      url: " http://127.0.0.1:8000"
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4NTk2ODI0LCJpYXQiOjE3MTg1OTMyMjQsImp0aSI6ImM4MzhjMWExNWM1NDQ1ZTViZmQ3YTdkZTlkZjkzYjEyIiwidXNlcl9pZCI6N30.Y5dOrE3N9_TZ3_9mLwfO5y2nosqw9_vHTPeTm5J-HNg
      token_empleado: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4NTk2ODQ0LCJpYXQiOjE3MTg1OTMyNDQsImp0aSI6IjdmODU3NTRmZTM0NzRkYzRiOWE3ZWY3MTEzMzljODFlIiwidXNlcl9pZCI6OH0.tx83JPDBCX9DSuqFlQvfVJ2U2kAhMiWsJs7qHh8h8Fs
    dataPropertyOrder:
      "&":
        - url
        - token
        - token_empleado
    color: null
    isPrivate: false
    metaSortKey: 1718500777864
    _type: environment
  - _id: jar_1415ce00bca21418c66ca3faba539dc90feb06d9
    parentId: wrk_a36edb13ade64d769b9b18508a853132
    modified: 1718500777867
    created: 1718500777867
    name: Default Jar
    cookies: []
    _type: cookie_jar
